project_id = "hbmifpeqquxhiaztchca"

[functions.create-partner-client]
verify_jwt = true

[functions.delete-partner]
verify_jwt = true

[functions.generate-meeting-ata]
verify_jwt = false

[functions.governance-pendencias-notifier]
verify_jwt = false

[functions.governance-reminders]
verify_jwt = false

[functions.guest-access]
verify_jwt = false

[functions.me]
verify_jwt = true

[functions.request-access]
verify_jwt = false

[functions.request-admin-access]
verify_jwt = false

[functions.request-partner-access]
verify_jwt = false

[functions.secretariat-search]
verify_jwt = false

[functions.setup-demo-users]
verify_jwt = false